### ISSUE TITLE
Canvas files with commas in their filenames don't work: JWT rejected: resource claim does not match URL path

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#106]
There are three parts to fixing this:

- [x] https://github.com/hypothesis/via3/issues/103 - Don't decode encoded commas in the /proxy/static/ (NGINX) endpoint 
- [x] https://github.com/hypothesis/via3/issues/104 - Don't decode encoded commas in the /pdf/ endpoint
- [x] https://github.com/hypothesis/via3/issues/105 - Don't decode encoded commas in the / endpoint

**Comment by seanh** [comment]
@jon-betts This is fixed now right?

**Comment by jon-betts** [comment]
I'm pretty sure this is done and fixed.
