### ISSUE TITLE
Release Via 3 for production LMS users

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#11]
**Confusingly this actually involves sending PRs to the LMS app**, to make it use Via 3, not sending PRs to Via 3. But the issue is in the Via 3 repo so that it can go in the milestone with other Via 3 issues.

Depends on:

- [x] [Set up monitoring and alerting for Via 3 #10](https://github.com/hypothesis/py-proxy/issues/10): we can't enable Via 3 in production until we have all the usual monitoring and alerting set up
- [x] [Decide on Elastic Beanstalk auto scaling settings for production Via 3 #14](https://github.com/hypothesis/py-proxy/issues/14)
- [x] [Decide on Elastic Beanstalk instance type and number of Gunicorn workers, for production Via 3 #15](https://github.com/hypothesis/py-proxy/issues/15)

Via 3 is already usable with the QA and production LMS apps behind a feature flag. Go to either <https://qa-lms.hypothes.is/flags> or <https://lms.hypothes.is/flags> and turn on <kbd>use_via3_url</kbd> to enable it in your browser. This card is to:

* Thoroughly test Via 3 in production behind a feature flag. It should be enough to test it in just Canvas:

  - [x] Test that production Via 3 works with PDF assignments (public URL) in Canvas
  - [x] Test that production Via 3 works with Canvas File assignments in Canvas
  - [x] Test that production Via 3 works with Google Drive assignments in Canvas
  - [x] Test that production Via 3 works with HTML assignments in Canvas (it should redirect to legacy Via, and the client login and groups integration should be working)
  - [x] Test that PDF, Canvas File, Google Drive and HTML assignments work in Canvas SpeedGrader

- [x] Enable qa-via3 for qa-lms for all users, without them having to turn on the feature flag. This can be done by changing the `VIA_URL` envvar in QA LMS (in Elastic Beanstalk)

- [x] Enable production via3 for production lms for all users, without them having to turn on the feature flag. This can be done by changing the `VIA_URL` envvar in prod LMS (in Elastic Beanstalk)

- [x] <del>Remove the  use_via3_url feature flag from LMS (including removing it from the https://lms.hypothes.is/flags and https://qa-lms.hypothes.is/flags pages)</del> Moved this to a separate card: https://github.com/hypothesis/via3/issues/80
