### ISSUE TITLE
Implement HTML rewriting

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#133]
Depends on:

- [ ] HTML testing spreadsheet: https://github.com/hypothesis/via3/issues/20
- [ ] Having an idea of how much rewriting needs to happen / what needs to be rewritten: https://github.com/hypothesis/via3/issues/7
- [ ] Having a proof-of-concept for how we'll do HTML rewriting: https://github.com/hypothesis/via3/issues/8

Once we have all of the above, we can implement and ship a production version of the HTML rewriting proxy.

**Comment by jon-betts** [comment]
I think this is probably better tracked with the milestone
