### ISSUE TITLE
Make Via HTML a separate component in production

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#247]
* [x] https://github.com/hypothesis/via3/issues/238 - Move the shared Via 3 logic into a separate component
* [x] https://github.com/hypothesis/via3/issues/233 - Separate Via HTML into a separate repo and product 
* [x] https://github.com/hypothesis/via3/issues/271 - Add a /_status end-point to Via HTML
* [x] https://github.com/hypothesis/via3/issues/234 - Get Via HTML deployed to live (it's deployed, but not working)
* [x] https://github.com/hypothesis/via3/issues/283 - Review Via HTML functionality and fix as appropriate
* [x] https://github.com/hypothesis/viahtml/pull/15 - ViaHTML Jenkins file
* [x] https://github.com/hypothesis/playbook/issues/434 - AWS env names
* [x] https://github.com/hypothesis/deployment/issues/145 - Move deployment directories to match various things

**Comment by jon-betts** [comment]
Done! At long last we're done! Now on to all the rest...
