### ISSUE TITLE
Make Via HTML the default for LMS and Via 3

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#248]
* [x] https://github.com/hypothesis/via3/issues/236 - Send X% of users from LMS to ViaHTML
* [x] Observe the performance of our subset of users
* [x] https://github.com/hypothesis/via3/issues/237 - Remove Via 3 HTML component from Via 3
* [x] https://github.com/hypothesis/via3/issues/245 - Remove the Via HTML feature flag from Via and LMS
* [x] https://github.com/hypothesis/via3/issues/244 - Make LMS and Via 3 use Via HTML by default

**Comment by jon-betts** [comment]
Done!
