### ISSUE TITLE
Get Via HTML to production quality

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#249]
* [x] https://github.com/hypothesis/via3/issues/243 - Via HTML test coverage should be made production quality
* [x] https://github.com/hypothesis/via3/issues/246 - Add appropriate monitoring and alerting for Via HTML
* [x] https://github.com/hypothesis/via3/issues/250 - Change the Via HTML AWS NGINX to allow larger headers
* [x] https://github.com/hypothesis/via3/issues/239 - Add an update-able blocklist file for Via HTML
* [x] https://github.com/hypothesis/via3/issues/240 - Via HTML should strip non-user sourced headers, like Cloudflare and Amazon
   * [x] https://github.com/hypothesis/viahtml/pull/16 - Missed some
* [x] https://github.com/hypothesis/via3/issues/241 - Via HTML should pass on sensible caching headers
* [x] https://github.com/hypothesis/via3/issues/242 - We should audit Via HTML cookie handling behavior
* [x] https://github.com/hypothesis/via3/issues/259 - Add support for `via.external_link_mode`
* [x] https://github.com/hypothesis/via3/issues/285 - Add a landing page
* [x] https://github.com/hypothesis/via3/issues/286 - Prevent proxying video content or block it - _Gave up and blocked it in the end_
