### ISSUE TITLE
Via HTML in production

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#251]
* [x] https://github.com/hypothesis/via3/issues/247 - Make Via HTML a separate component in production
* [x] https://github.com/hypothesis/via3/issues/249 - Get Via HTML to production quality
* [x] https://github.com/hypothesis/via3/issues/248 - Make Via HTML the default for LMS and Via 3

**Comment by jon-betts** [comment]
Done!
