### ISSUE TITLE
Review Via HTML functionality and fix as appropriate

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#283]
For https://github.com/hypothesis/via3/issues/247, Via HTML has been deployed to live, but it's not a happy bunny. We need to:

 * Check why `wombat.js` and other static content isn't loading (not being generated on deploy / docker create?)
 * After that give it a general once over
 * Generally check over a number of other tickets that have gone out but couldn't be tested in live before
   * Stripping infra headers
   * Passing caching headers for Cloudflare
   * Open in new tab
 * If things are working, then tidy up the tickets etc linked from: https://github.com/hypothesis/via3/issues/249

## Discovered issues

Add tickets / fixes for immediate fixing:

 * [x] Static content isn't being included in the docker image
 * Deployments aren't working automatically yet:
   * [x] https://github.com/hypothesis/viahtml/pull/15 - ViaHTML Jenkins file
   * [x] https://github.com/hypothesis/playbook/issues/434 - AWS env names
   * [x] https://github.com/hypothesis/deployment/issues/145 - Move deployment directories to match various things

Before we go live

 * [x] https://github.com/hypothesis/via3/issues/285 - No landing page - Not really discovered, but needs addressing before release
 * [x] https://github.com/hypothesis/via3/issues/286 - It appears we _are_ proxying video content (I thought we weren't) so that needs to be fixed or blocked
    * On closer reading I think `pywb` doesn't proxy _Flash_ based video anymore, but that's more because nobody uses it and it's broken I suspect

Non blocking items (do it sometime maybe):
 * [x] https://github.com/hypothesis/via3/issues/287 - Similar for audio content: https://qa-viahtml3.hypothes.is/proxy/https://www.vox.com/pages/podcasts
 * [x] https://github.com/hypothesis/via3/issues/288 - We don't rewrite URLs in `manifest.json` files: https://twitter.com/bascule/status/1307440596668182528?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1307440596668182528%7Ctwgr%5Eshare_3&ref_url=https%3A%2F%2Fwww.theguardian.com%2Ftechnology%2F2020%2Fsep%2F21%2Ftwitter-apologises-for-racist-image-cropping-algorithm

**Comment by jon-betts** [comment]
I've reviewed the first 25 sites from the HTML test harness, and everything is about as I'd expect. Things which were broken before are still broken, but mostly it's working as expected.

Tickets have been filed for outstanding parts.
