### ISSUE TITLE
Create frontend app for YouTube video transcript annotation

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#904]
As part of https://github.com/hypothesis/product-backlog/issues/1433 we need somewhere to host the web app that contains the video player, transcript and client. See https://github.com/hypothesis/product-backlog/issues/1433 for links to design docs and UI mocks.

This will likely use the same tech stack as the frontend mini-apps in the LMS app.

- [x] Add basic infrastructure for video player app (https://github.com/hypothesis/via/pull/905, https://github.com/hypothesis/via/pull/907, https://github.com/hypothesis/via/pull/908, https://github.com/hypothesis/via/pull/909)
- [x] Add transcript display, which indicates current video segment and scrolls as video plays (https://github.com/hypothesis/via/pull/920)
- [x] Add button to sync transcript display with current video position (https://github.com/hypothesis/via/pull/922)
- [x] Add search box to transcript which filters segments to those matching search terms (https://github.com/hypothesis/via/pull/929)
- [x] Exclude timestamps from captured selections (https://github.com/hypothesis/via/pull/931)
- [ ] Display client sidebar side-by-side with transcript when the sidebar is open (https://github.com/hypothesis/via/issues/954)
- [x] Fix selections spanning multiple segments in Safari (see https://github.com/hypothesis/via/pull/920#issuecomment-1547610108)
- [ ] Ensure `TextQuoteSelector` selectors in annotations don't capture text from outside the transcript (eg. from text in controls). This might be part of https://github.com/hypothesis/via/issues/940.
- [ ] Prevent users from annotating outside of the transcript in the video player? (ie. don't show the Annotate/Highlight controls if the user selects text in the controls UI etc.) (https://github.com/hypothesis/via/issues/940)
- [x] Add keyboard shortcuts for player (https://github.com/hypothesis/via/issues/939)

**Comment by robertknight** [comment]
The basic infrastructure has been added in https://github.com/hypothesis/via/pull/905, https://github.com/hypothesis/via/pull/907, https://github.com/hypothesis/via/pull/908 and https://github.com/hypothesis/via/pull/909.

**Comment by robertknight** [comment]
I'm going to close this issue now as "generally done", and leave the remaining polish for other issues.
